version: '2'
services:
   web:
     build: .
     env_file:
       - secrets.env
     expose:
       - "15134"
     networks:
       - proxy
     environment:
       VIRTUAL_HOST: home.homb.it
       VIRTUAL_PORT: "15134"
       HTTPS_METHOD: noredirect
       DYNDNS_HOST: home.homb.it
       LETSENCRYPT_HOST: home.homb.it
       LETSENCRYPT_EMAIL: home@homb.it
     restart: always

networks:
  proxy:
    external:
      name: proxy
